language: java
sudo: enabled
services:
- docker
cache:
  directories:
  - ${HOME}/.m2

jdk:
- oraclejdk8
before_script: cd feinstaubr-web
script:
- echo 1.${TRAVIS_BUILD_NUMBER}>src/main/resources/version
- mvn install
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build . -t albert0815/feinstaub:1.${TRAVIS_BUILD_NUMBER}
docker push albert0815/feinstaub

