language: java
sudo: enabled
services:
- docker
cache:
  directories:
  - ${HOME}/.m2
  - ${HOME}/google-cloud-sdk

jdk:
- oraclejdk8
before_script: cd feinstaubr-web
script:
- mvn install
after_success:
- export CLOUDSDK_CORE_DISABLE_PROMPTS=1
- curl https://sdk.cloud.google.com | bash
- ${HOME}/google-cloud-sdk/bin/gcloud components install kubectl
- ${HOME}/google-cloud-sdk/bin/gcloud version
- ${HOME}/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ../gce.json
- ${HOME}/google-cloud-sdk/bin/gcloud config set project feinstaubr
- docker build . -t gcr.io/feinstaubr/feinstaubr-web:latest
- ${HOME}/google-cloud-sdk/bin/gcloud docker -- push gcr.io/feinstaubr/feinstaubr-web:latest
- ${HOME}/google-cloud-sdk/bin/gcloud container clusters get-credentials feinstaubr-cluster --zone europe-west3-a
- ${HOME}/google-cloud-sdk/bin/kubectl apply -f kubernetes kubernetes-feinstaubr-deployment.yaml


before_install:
- openssl aes-256-cbc -K $encrypted_e4b7d3b0f372_key -iv $encrypted_e4b7d3b0f372_iv
  -in gce.json.enc -out gce.json -d
