language: java

sudo: enabled

services:
  - docker

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

before_script: cd feinstaubr-web

script:
  - mvn install


after_success:
  docker build . -t feinstaubr-web