apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:10.1
          name: postgres
          env:
            - name: POSTGRES_USER
              value: feinstaub
            - name: POSTGRES_PASSWORD
              value: feinstaub
            - name: POSTGRES_DB
              value: feinstaub
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          gcePersistentDisk:
            pdName: postgres-disk
            fsType: ext4